### ISSUE TITLE
cannot convert 'String' to 'const char*' for argument '1' to 'int atoi(const char*)'

### ISSUE THREAD

**Issue by dzeitman** [spark/InternetButton#1]
Veryfing code using this library in Particle Build fails with this error:

```
InternetButton/InternetButton.cpp:235:42: error: cannot convert 'String' to 'const char*' for argument '1' to 'int atoi(const char*)'
         octave = atoi(note.substring(1,2))

Looks like a syntax error...   "did anyone bother to test this"?
```

**Comment by davidfekke** [comment]
I am getting it.

**Comment by jenesaisdiq** [comment]
Hey guys, sorry I didn't see the notification. Appears to work fine with Photons but breaks with Cores. @dzeitman are you using a Core?

**Comment by jenesaisdiq** [comment]
Ok, would @dzeitman and @davidfekke mind testing it for me with Cores? Rev'd up to 0.1.5 now. There are a couple of steps you'll need to make sure you're getting the latest version:
1) In the libraries view, click "Refresh Libraries"
2) Reload the page (Build) just in case
3) Double check that the Internet Button library version you're seeing is 0.1.5
4) Either a) remove the library from your current code and readd it or, easier, b) just "Use an Example" from the library again, and you'll be sure to have it.

**Comment by jenesaisdiq** [comment]
Sounds like this one's fixed.
