### ISSUE TITLE
Error retrieving device id

### ISSUE THREAD

**Issue by jeremykeen** [spark/InternetButton#2]
Uncaught TypeError: Cannot read property 'id' of undefinedsendApiRequest @ controlKnob.html:55(anonymous function) @ controlKnob.html:73

pull request to be submitted to fix.

**Comment by shaiss** [comment]
Thanks for fixing that, I updated my code and confirmed the pull request fixes the issue!

**Comment by jenesaisdiq** [comment]
Nice! Will accept PR.
